# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "parallel"
batch_size_run: 8

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixing_embed_dim: 32
mixer:
optimiser: "Adam"
SGDR: True

name: "iql_smac_trans_SGDR"

# Transformer Parameters
agent: "transformer"
n_embd: 128
n_layer: 2
n_head: 4
embd_pdrop: 0.1
length: 8
lr: 0.0001
